version: '3.8'

services:
  consumer:
    build: .
    container_name: spark-transaction-consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: user-transactions
      KAFKA_ALERTS_TOPIC: alerts
      KAFKA_SEGMENTS_TOPIC: user-segments
      SPARK_MASTER: local[*]
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: spark-network